version: "3.8"

services:
  app:
    build: .
    container_name: app
    env_file: .env
    expose:
      - "${PORT}"
    depends_on:
      - postgres
    networks:
      - web
      - db

  worker:
    build: .
    container_name: queue_worker
    command: node src/processor.js
    env_file: .env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - web
      - db

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
    driver: bridge
  db:
    driver: bridge
