version: "3.8"

services:
  app:
    build: .
    container_name: app
    env_file: .env
    expose:
      - "${PORT}"
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - web

networks:
  web:
    driver: bridge
